### ISSUE TITLE
Getting error while running the code

### ISSUE THREAD

**Issue by Jacksonm93** [f4T1H21/Arbitrage-Bot-Code-Library#1]
![image](https://user-images.githubusercontent.com/19143790/205485164-4337879c-c78b-4ca5-bc42-1ab0565418a1.png)
```
import libarbitrage
from time import sleep


APIKEY = 'efd9a9bd4af942bf99bc68edc53a9576'
tokens = ['eth', 'btc', 'ftt', 'aave', 'usdc',
          'usdt']  # Tokens to analyze between
dexes = ['uniswap', 'sushiswap']  # DEXes to analyze
revenue = 1.5  # Minimum amount of revenue in percentage per one USDT
libarbitrage.arbitrage(APIKEY, tokens, revenue)

arbitrage_data = libarbitrage.getArbitrageData()
type(arbitrage_data)

print(len(arbitrage_data))
print('Done')
```

I tried to test this code and I'm getting this error below. 
Can you pls share a sample code

![image](https://user-images.githubusercontent.com/19143790/205485228-42835c75-1b05-42c9-90dd-8b16c511b140.png)

**Comment by f4T1H21** [comment]
Hello, you should write either all the arguments respectively (according to their definition order), or some of them with corresponding keywords when passing to the function. Please see the related part of [README](..#non-interactive-developer-mode), try with the given codes and inform about the result.

**Comment by f4T1H21** [comment]
@Jacksonm93
Any updates?

**Comment by f4T1H21** [comment]
Assuming the problem has been solved.
